definitions:
  entities.Ans:
    properties:
      id:
        type: integer
      isCorrect:
        type: boolean
      name:
        type: string
    type: object
  entities.AnswerBase:
    properties:
      isCorrect:
        type: boolean
      name:
        type: string
    type: object
  entities.AnswerChange:
    properties:
      id:
        type: integer
      value:
        type: boolean
    type: object
  entities.Question:
    properties:
      answers:
        items:
          $ref: '#/definitions/entities.Ans'
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  entities.QuestionAdd:
    properties:
      id_answer:
        type: integer
      id_question:
        type: integer
    type: object
  entities.QuestionBase:
    properties:
      answers:
        items:
          $ref: '#/definitions/entities.Ans'
        type: array
      description:
        type: string
      name:
        type: string
    type: object
  entities.TeachChangePassword:
    properties:
      id:
        type: integer
      password:
        type: string
    type: object
  entities.TeachCreate:
    properties:
      email:
        type: string
      nick:
        type: string
      password:
        type: string
    type: object
  entities.TeachLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.TestAdd:
    properties:
      id_question:
        type: integer
      id_test:
        type: integer
    type: object
  entities.TestBase:
    properties:
      level:
        type: integer
      name:
        type: string
      questions:
        items:
          $ref: '#/definitions/entities.Question'
        type: array
      speed:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /answer/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: AnswerID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get answer
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get answer
      tags:
      - answer
  /answer/change:
    put:
      consumes:
      - application/json
      parameters:
      - description: answer change
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.AnswerChange'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change answer
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change iscorrect answer
      tags:
      - answer
  /answer/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: answer create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.AnswerBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created answer
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create answer
      tags:
      - answer
  /question/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: QueID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get Que
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Que
      tags:
      - Que
  /question/add:
    put:
      consumes:
      - application/json
      parameters:
      - description: Que add ans
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.QuestionAdd'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully add ans
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add Answer to Que
      tags:
      - Que
  /question/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Que create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.QuestionBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created Que
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Que
      tags:
      - Que
  /teach/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: TeachID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get teach
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get teach
      tags:
      - teach
  /teach/change:
    put:
      consumes:
      - application/json
      parameters:
      - description: teach change pwd
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.TeachChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change pwd
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: ChangePWD teach
      tags:
      - teach
  /teach/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: teach create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.TeachCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created teach
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create teach
      tags:
      - teach
  /teach/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: TeachID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully delete teach
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete teach
      tags:
      - teach
  /teach/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: teach login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.TeachLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login teach
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login teach
      tags:
      - teach
  /test/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: TestID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get test
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get test
      tags:
      - test
  /test/add:
    put:
      consumes:
      - application/json
      parameters:
      - description: test add que
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.TestAdd'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully add test
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add que to test
      tags:
      - test
  /test/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: test create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entities.TestBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created test
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create test
      tags:
      - test
swagger: "2.0"
